-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 21:33:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema livrocaixa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema livrocaixa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livrocaixa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `livrocaixa` ;

-- -----------------------------------------------------
-- Table `livrocaixa`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cli_celular` VARCHAR(15) NOT NULL,
  `cli_fantasia` VARCHAR(40) NOT NULL,
  `cli_razao` VARCHAR(40) NULL DEFAULT NULL,
  `cli_nome` VARCHAR(40) NULL DEFAULT NULL,
  `cli_telefone` VARCHAR(15) NULL DEFAULT NULL,
  `cli_email` VARCHAR(30) NULL DEFAULT NULL,
  `cli_cep` VARCHAR(9) NULL DEFAULT NULL,
  `cli_uf` VARCHAR(3) NULL DEFAULT NULL,
  `cli_cidade` VARCHAR(30) NULL DEFAULT NULL,
  `cli_endereco` VARCHAR(40) NULL DEFAULT NULL,
  `cli_end_numero` VARCHAR(20) NULL DEFAULT NULL,
  `cli_complemento` VARCHAR(30) NULL DEFAULT NULL,
  `cli_end_bairro` VARCHAR(30) NULL DEFAULT NULL,
  `cli_data_nascimento` DATE NULL DEFAULT NULL,
  `cli_contrato` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `livrocaixa`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`produto` (
  `id_Produto` INT NOT NULL AUTO_INCREMENT,
  `Produto` VARCHAR(45) NOT NULL,
  `Quantidade` FLOAT NULL DEFAULT NULL,
  `Data_inclusao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Data_atualizacao` DATE NULL DEFAULT NULL,
  `unidade_medida` VARCHAR(3) NULL DEFAULT NULL,
  `prod_custo` FLOAT NULL DEFAULT NULL,
  `prod_venda` FLOAT NULL DEFAULT NULL,
  `prod_ativo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Produto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livrocaixa`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`entrada` (
  `id_Entrada` INT NOT NULL,
  `Custo` FLOAT NULL DEFAULT NULL,
  `Quantidade` FLOAT NULL DEFAULT NULL,
  `Data` TIMESTAMP NULL DEFAULT NULL,
  `Produto_id_Produto` INT NOT NULL,
  PRIMARY KEY (`id_Entrada`),
  INDEX `fk_Entrada_Produto_idx` (`Produto_id_Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Entrada_Produto`
    FOREIGN KEY (`Produto_id_Produto`)
    REFERENCES `livrocaixa`.`produto` (`id_Produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livrocaixa`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`estoque` (
  `id_Estoque` INT NOT NULL,
  `Est_data` DATE NULL DEFAULT NULL,
  `Saldo_Anterior` FLOAT NULL DEFAULT NULL,
  `Credito_Debito` VARCHAR(4) NULL DEFAULT NULL,
  `Quantidade` FLOAT NULL DEFAULT NULL,
  `Saldo_Final` FLOAT NULL DEFAULT NULL,
  `Produto_id_Produto` INT NOT NULL,
  PRIMARY KEY (`id_Estoque`),
  INDEX `fk_Estoque_Produto1_idx` (`Produto_id_Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_id_Produto`)
    REFERENCES `livrocaixa`.`produto` (`id_Produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livrocaixa`.`fechamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`fechamento` (
  `id_fecha` INT NOT NULL AUTO_INCREMENT,
  `fecha_mes` INT NOT NULL,
  `fecha_saldo` FLOAT NOT NULL,
  `fecha_int` INT NOT NULL,
  `fecha_ano` INT NOT NULL,
  PRIMARY KEY (`id_fecha`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livrocaixa`.`formas_pgto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`formas_pgto` (
  `id_forma` INT NOT NULL AUTO_INCREMENT,
  `forma_descricao` VARCHAR(30) NOT NULL,
  `forma_parcelas` INT NULL DEFAULT NULL,
  `forma_ativo` TINYINT(1) NOT NULL,
  `forma_taxa` FLOAT NULL DEFAULT NULL,
  `forma_dias_comp` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_forma`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livrocaixa`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `grupo_descricao` VARCHAR(30) NOT NULL,
  `grupo_tipo` VARCHAR(4) NOT NULL,
  `grupo_ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livrocaixa`.`movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`movimento` (
  `id_movimento` INT NOT NULL AUTO_INCREMENT,
  `id_grupo` INT NOT NULL,
  `id_forma` INT NOT NULL,
  `mov_valor` FLOAT NOT NULL,
  `mov_tipo` VARCHAR(4) NOT NULL,
  `mov_parcela` INT NOT NULL,
  `mov_descricao` VARCHAR(40) NOT NULL,
  `mov_data` TIMESTAMP NULL DEFAULT NULL,
  `mov_ativo` TINYINT(1) NOT NULL,
  `mov_data_venc` DATE NOT NULL,
  `mov_id_pai` INT NOT NULL,
  `mov_num_parcela` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_movimento`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livrocaixa`.`saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`saida` (
  `id_Saida` INT NOT NULL,
  `S_Custo` FLOAT NULL DEFAULT NULL,
  `S_Quantidade` FLOAT NULL DEFAULT NULL,
  `S_Data` TIMESTAMP NULL DEFAULT NULL,
  `Produto_id_Produto` INT NOT NULL,
  PRIMARY KEY (`id_Saida`),
  INDEX `fk_Entrada_Produto_idx` (`Produto_id_Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Entrada_Produto0`
    FOREIGN KEY (`Produto_id_Produto`)
    REFERENCES `livrocaixa`.`produto` (`id_Produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livrocaixa`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrocaixa`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `cargo` VARCHAR(15) NOT NULL,
  `adm` TINYINT(1) NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `empresa` VARCHAR(10) NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
